# headless service
# service
# statefulset

apiVersion: v1
kind: Secret
metadata: 
  name: rabbitmq-secret
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: rabbitmq
    tier: database
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: rabbitmq
    tier: database
spec:
  clusterIP: None
  selector: 
    project: roboshop
    environment: dev
    component: rabbitmq
    tier: database
  ports: 
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: rabbitmq
    tier: database
spec:
  selector: 
    project: roboshop
    environment: dev
    component: rabbitmq
    tier: database
  ports: 
    - protocol: TCP
      port: 5672 # service port
      targetPort: 5672 # container port

---

apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: rabbitmq
  namespace: roboshop
  labels: 
    project: roboshop
    environment: dev
    component: rabbitmq
    tier: database
spec: 
  selector:
    matchLabels: 
      project: roboshop
      environment: dev
      component: rabbitmq
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "rabbitmq-headless" # this should be headless service
  replicas: 3 # by default it is 1
  template: 
    metadata: 
      labels: 
        project: roboshop
        environment: dev
        component: rabbitmq
        tier: database
    spec: 
      containers:
        - name: rabbitmq
          image: aneelp/rabbitmq:v1
          volumeMounts: 
            - name: rabbitmq-data
              mountPath: /data # This is nothing but PVC, you can directly create here
  volumeClaimTemplates: 
    - metadata:
        name: rabbitmq-data
      spec: 
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs" 
        resources:
          requests: 
            storage: 2Gi