# headless service
# service
# statefulset

apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mongodb
    tier: database
spec:
  clusterIP: None
  selector: 
    project: roboshop
    environment: dev
    component: mongodb
    tier: database
  ports: 
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mongodb
    tier: database
spec:
  selector: 
    project: roboshop
    environment: dev
    component: mongodb
    tier: database
  ports: 
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port

---

apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: mongodb
  namespace: roboshop
  lables: 
    project: roboshop
    environment: dev
    component: mongodb
    tier: database
spec: 
  selector:
    matchLables: 
      project: roboshop
      environment: dev
      component: mongodb
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "mongodb-headless" # this should be headless service
  replicas: 3 # by default it is 1
  template: 
    metadata: 
      labels: 
      project: roboshop
      environment: dev
      component: mongodb
      tier: database
    spec: 
      containers:
        - name: mongodb
          image: aneelp/mongodb:v1
          volumeMounts: 
            - name: mongodb-data
              mountPath: /data/db # This is nothing but PVC, you can directly create here
  volumeClaimTemplates: 
    - metadata:
        name: mongodb-data
      spec: 
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs" 
        resources:
          requests: 
            storage: 2Gi