# headless service
# service
# statefulset
# secret for username and password

apiVersion: v1
kind: Secret
metadata: 
  name: mysql-secret
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mysql
    tier: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="
  
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mysql
    tier: database
spec:
  clusterIP: None
  selector: 
    project: roboshop
    environment: dev
    component: mysql
    tier: database
  ports: 
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mysql
    tier: database
spec:
  selector: 
    project: roboshop
    environment: dev
    component: mysql
    tier: database
  ports: 
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port

---

apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: mysql
  namespace: roboshop
  labels: 
    project: roboshop
    environment: dev
    component: mysql
    tier: database
spec: 
  selector:
    matchLabels: 
      project: roboshop
      environment: dev
      component: mysql
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless" # this should be headless service
  replicas: 2 # by default it is 1
  template: 
    metadata: 
      labels: 
        project: roboshop
        environment: dev
        component: mysql
        tier: database
    spec: 
      containers:
        - name: mysql
          image: aneelp/mysql:v1
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts: 
            - name: mysql-data
              mountPath: /var/lib/mysql # This is nothing but PVC, you can directly create here
  volumeClaimTemplates: 
    - metadata:
        name: mysql-data
      spec: 
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs" 
        resources:
          requests: 
            storage: 2Gi